# Generated by Django 5.1.1 on 2024-10-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_blog_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_created_at'], 'verbose_name': 'Blog_Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
