# Generated by Django 5.1.1 on 2024-10-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
